# Generated by Django 3.1 on 2020-08-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.GenericIPAddressField(verbose_name='ip')),
                ('server_port', models.IntegerField(verbose_name='PORT')),
                ('server_user', models.CharField(max_length=100, verbose_name='user')),
                ('server_pwd', models.CharField(max_length=256, verbose_name='password')),
            ],
            options={
                'verbose_name': 'IP ADDR',
                'verbose_name_plural': 'IP ADDR',
            },
        ),
    ]
