# Generated by Django 3.1 on 2020-08-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='课程名称')),
            ],
        ),
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100, verbose_name='学生姓名')),
                ('stu_sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=6, verbose_name='性别')),
            ],
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_name', models.CharField(max_length=100, verbose_name='教师名称')),
                ('tea_sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=6, verbose_name='性别')),
                ('tea_tel', models.CharField(max_length=11, verbose_name='手机号')),
                ('tea_course', models.ManyToManyField(to='login.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='stu_course',
            field=models.ManyToManyField(to='login.Stu'),
        ),
    ]
