# Generated by Django 3.1 on 2020-08-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200820_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='stu_course',
        ),
        migrations.RemoveField(
            model_name='tea',
            name='tea_course',
        ),
        migrations.AddField(
            model_name='stu',
            name='stu_password',
            field=models.CharField(default='', max_length=256, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='tea',
            name='tes_password',
            field=models.CharField(default='', max_length=256, verbose_name='密码'),
        ),
    ]
