# Generated by Django 2.1.1 on 2018-09-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rolemanage',
            fields=[
                ('roleid', models.AutoField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=30)),
                ('power', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Superadmin',
            fields=[
                ('adminid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=40)),
                ('role', models.CharField(max_length=300)),
                ('customrole', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=300)),
                ('ctime', models.CharField(max_length=100)),
            ],
        ),
    ]
